### ISSUE TITLE
Lightning dashboard still accessible from footer  

### ISSUE THREAD

**Issue by alamshafil** [litecoin-foundation/ltcspace#3]
### Description

Lightning dashboard still accessible from footer. I believe this is not the inteded behavior since the tab was removed from the top navbar and does not function.

#### Version

(v2.6.0-dev) [[2f561d27](https://github.com/litecoin-foundation/ltcspace/commit/2f561d27)]

### Screenshots

![Screenshot from 2023-07-03 22-18-51](https://github.com/litecoin-foundation/ltcspace/assets/36016500/72b5c545-e55b-4023-a596-b97e6b305590)

**Comment by losh11** [comment]
Fixed w/ 109ffbf.
Thank you for finding this issue.
