### ISSUE TITLE
Add the testnet network

### ISSUE THREAD

**Issue by Sayrix** [litecoin-foundation/ltcspace#4]
Please add the testnet network, that would be great and easy for you, thats just another node and the testnet network is not heavy

**Comment by losh11** [comment]
Working on it! All the code should be working, and locally hosting would be simple. However deploying Litecoin Space to a product high availability server takes hours of work.

**Comment by Sayrix** [comment]
tysm

**Comment by Sayrix** [comment]
Hi, i seen that you released the testnet version, here is a PR about a pool on the testnet: https://github.com/litecoin-foundation/mining-pools-ltc/pull/2

**Comment by losh11** [comment]
Done! https://litecoinspace.org/testnet
